const CRITERIA = {
  안전인증: [
    "가스라이터",
    "가정용 압력냄비 및 압력솥",
    "가습기",
    "교류전원을 사용하는 발 보온기",
    "교류전원을 사용하는 전기찜질기",
    "교류전원을 사용하는 주방용 전동기기",
    "교류전원을 사용하는 전격 살충기",
    "그 밖에 유사한 기기",
    "냉방기",
    "단전지",
    "램프홀더",
    "리튬이차단전지",
    "모발관리기",
    "물놀이기구",
    "변압기",
    "비비탄 총",
    "스위치",
    "안정기 및 램프 제어장치",
    "안정기내장형 램프",
    "연결부품",
    "일반조명기구",
    "자동차용 재생타이어",
    "전기 냉장ㆍ냉동기기",
    "전기건조기",
    "전기기기용 스위치",
    "전기담요 및 매트, 전기침대",
    "전기다리미 및 전기프레스기",
    "전기마사지기",
    "전기설비용 부속품",
    "전기세탁기 및 탈수기",
    "전기액체가열기기",
    "전기온수기",
    "전기청소기",
    "전기충전기",
    "전선",
    "전압조정기",
    "전자개폐기",
    "전자레인지",
    "전열기구",
    "전원필터",
    "주방용전열기구",
    "직류전원장치",
    "차단기",
    "커패시터",
    "케이블 및 코드류",
    "팬, 레인지 후드",
    "퓨즈",
    "화장실용 전기기기",
  ],
  안전확인: [
    "가정용 전동재봉기",
    "건전지",
    "게임기구",
    "고령자용 보행보조차",
    "고령자용 보행차",
    "고주파웰더",
    "공기청정기",
    "관상 및 애완용 전기기기",
    "과일 껍질깎이",
    "구강청결기",
    "교류전원을 사용하는 전동공구",
    "그 밖에 유사한 기기",
    "기름난로",
    "기타 램프",
    "기타 조명기구",
    "기포발생기기",
    "노트북컴퓨터",
    "등산용 로프",
    "디스크 플레이어",
    "디지털 도어록",
    "디지털TV",
    "리튬이차전지시스템",
    "롤러스포츠 보호장구",
    "모니터",
    "문서 세단기",
    "물수건 마는 기기 및 포장기기",
    "미끄럼 방지 타일",
    "백열등기구",
    "복사기",
    "빙삭기",
    "사우나기기",
    "산소이온발생기",
    "서비스기기",
    "수도 동결 방지기",
    "수유패드",
    "스노보드",
    "스케이트보드",
    "스키용구",
    "스포츠용 구명복",
    "승차용 안전모",
    "식기세척기 및 식기건조기",
    "실내용 바닥재",
    "오디오시스템",
    "오디오프로세서",
    "온열팩",
    "운동용 안전모",
    "영상프로세서",
    "음식물처리기",
    "이·미용기기",
    "이륜자전거",
    "자동판매기",
    "자동차용 브레이크액",
    "자동차용 타이어",
    "전기기기용 제어소자",
    "전기가열기기",
    "전기보온기 및 전기온장고",
    "전기분무기",
    "전기세척기",
    "전기소독기",
    "전기에어커튼",
    "전기욕조",
    "전기 용해기",
    "전기온수매트",
    "전기용접기",
    "전기의자 및 전동침대",
    "전기정수기",
    "전기집진기",
    "전기차 충전기",
    "전기찜질기",
    "전기헬스기구",
    "전기훈증기",
    "전격 살충기",
    "전동보드",
    "전력변환장치",
    "전지",
    "제습기",
    "주방용 전동기기",
    "천공기",
    "컴프레서",
    "컴퓨터용 전원공급장치",
    "코팅기",
    "텔레비전수상기",
    "팬코일유닛",
    "폐열 회수 환기장치",
    "프린터",
    "프로젝터",
    "해충퇴치기",
    "헬스기구",
    "휴대용 레이저용품",
    "휴대용 예초기의 날 및 보호덮개",
    "방전램프",
    "유체펌프",
    "무정전공급장치",
  ],

  공급자적합성확인: [
    "A/D 및 D/A 신호변환기",
    "A/V신호수신기",
    "CATV방송수신기",
    "CCTV 카메라",
    "IPTV용 셋톱박스",
    "감자 탈피기",
    "공중전화 데이터전송 단말기",
    "교통카드 충전기",
    "금전등록기",
    "동전계수기",
    "디지털 CATV 셋톱박스",
    "디지털 재변조형 주파수변환기",
    "라디오수신기",
    "리시버",
    "모듈레이터",
    "무선기기",
    "번호표 발행기",
    "보풀 제거기",
    "비디오게임기구",
    "비디오카메라",
    "비디오폰",
    "새싹 및 콩나물 재배기",
    "생활무선국용 무전기",
    "스캐너",
    "신용카드조회 단말기기",
    "신호변환장치",
    "실물화상기",
    "앰프",
    "애완동물 목욕기",
    "어학실습기",
    "오디오 및 비디오 학습기",
    "원격제어방송기기",
    "위성방송수신기",
    "위치기반 무선기기",
    "음성 및 영상분배기",
    "음성기록계",
    "음성플레이어",
    "음질조절기",
    "입체영상기",
    "재단기",
    "적외선ㆍ자외선방사 피부관리기",
    "전기 빵 자르개",
    "전기 정미기",
    "전기 작동 도어록",
    "전기분수기",
    "전기소자기",
    "전기시계",
    "전기주류숙성기",
    "전동타자기",
    "전동형 롤스크린",
    "전자시계",
    "전자악기",
    "전자칠판 및 보드",
    "전화기",
    "전화기능 내장 복합단말기기",
    "제본기",
    "지상파텔레비전방송 신호처리기",
    "지폐계수기",
    "직류전원을 사용하는 공기청정기",
    "직류전원을 사용하는 전동공구",
    "착유기",
    "컴프레서 게이트",
    "턴테이블",
    "투영기",
    "튜너",
    "특정 용도의 단말기기",
    "팩시밀리기기",
    "편집기",
    "형광램프용 스타터",
    "휴대형 무선통신기기",
    "영상기록계",
    "영상수신기 및 변환기",
    "영상전송기",
  ],
};

const criteriaString = JSON.stringify(CRITERIA, null, 2); // Use 2 spaces for indentation

export const PROMPT = {
  init: {
    system: `You are a frontline customer support agent, specializing in general inquiries related to KC certification.
    Be concise in your responses.
    You can chat with customers and help them with basic questions, but if the customer is having a KC certification problem, do not try to answer the question directly or gather information.
    Instead, immediately transfer them to the **CERTIFICATION SUPPORT TEAM** by asking the user to hold for a moment. Otherwise, just respond **CONVERSATIONALLY**. every response should be in korean`,
  },
  routing: {
    system: `You are an expert customer support routing system. Your job is to detect whether a customer support representative is routing a user to a **CERTIFICATION SUPPORT TEAM** or if they are just responding **CONVERSATIONALLY**.`,

    user: `The previous conversation is an interaction between a customer support representative and a user. Extract whether the representative is routing the user to a **CERTIFICATION SUPPORT TEAM**, or whether they are just responding **CONVERSATIONALLY**. Respond with a JSON object containing a single key called "nextRepresentative" with one of the following values:
    If they want to route the user to the **CERTIFICATION SUPPORT TEAM**, respond only with the word "CERTIFICATION"
    Otherwise, respond only with the word "RESPOND".`,
  },
  certification: {
    system: `You are an expert certification support specialist for KC certification, a company that sells computers. Help the user to the best of your ability, but be concise in your responses. 
    You are a classifier tasked with identifying the required KC certification type for a product item provided by the user. Your classification **must** be based **solely** on the provided 'KC Certification Product Standard Table'. Do not use any information outside of this table or your prior knowledge.
    Help the user to the best of your ability, but be concise in your responses.
    ---------
    KC Certification Product Standard Table:
    ${criteriaString}
    ---------
    EXAMPLES:
    - '무선 진공 청소기'는 '안전인증' 입니다.
    - '쌍꺼풀용 테이프'는 '공급자적합성확인' 대상 생활용품입니다.
    - '고령자용 보행보조차'는 '공급자적합성확인' 대상 전기용품입니다.
    - 적합한 품목이 없어서 KC인증 대상인지 확인이 어렵습니다.
    - '전기온수매트'는 '안정확인' 대상 제품입니다.
    - '실물화상기'는 '안전확인' 인증을 받아야합니다.
    `,
  },
};
