const CRITERIA = {
  안전인증대상제품: {
    전기용품: {
      "전선 및 전원코드": ["전선", "케이블 및 코드류"],
      "전기기기용 스위치": {
        품목: ["스위치", "전자개폐기"],
        비고: "기계ㆍ기구에 부착되는 특수구조인 것 및 방폭형은 제외",
      },
      "전원용 커패시터 및 전원필터": {
        품목: ["커패시터", "전원필터"],
        비고: "100Hz 이하인 것만 해당",
      },
      "전기설비용 부속품 및 연결 부품": {
        품목: ["전기설비용 부속품", "연결부품"],
        비고: "방폭형은 제외",
      },
      "전기용품 보호용 부품": ["퓨즈", "차단기"],
      절연변압기: {
        품목: ["변압기", "전압조정기"],
        비고: "정격용량 5kVA 이하, 특수구조는 제외",
      },
      전기기기: {
        품목: [
          "전기청소기",
          "전기다리미 및 전기프레스기",
          "주방용전열기구",
          "전기세탁기 및 탈수기",
          "모발관리기",
          "교류전원을 사용하는 주방용 전동기기",
          "전기액체가열기기",
          "전기담요 및 매트, 전기침대",
          "교류전원을 사용하는 전기찜질기",
          "교류전원을 사용하는 발 보온기",
          "전기온수기",
          "전기 냉장ㆍ냉동기기",
          "전자레인지",
          "전기충전기",
          "전기건조기",
          "전열기구",
          "전기마사지기",
          "냉방기",
          "교류전원을 사용하는 전격 살충기",
          "팬, 레인지 후드",
          "화장실용 전기기기",
          "가습기",
          "그 밖에 유사한 기기",
        ],
        비고: "정격입력 10kW 이하, 방폭형은 제외",
      },
      전동공구: [],
      "오디오ㆍ비디오 응용기기": [],
      정보ㆍ통신ㆍ사무기기: {
        품목: ["직류전원장치", "단전지", "그 밖에 유사한 기기"],
        비고: "기계ㆍ기구류에 부착되는 특수구조는 제외",
      },
      조명기기: [
        "램프홀더",
        "일반조명기구",
        "안정기 및 램프 제어장치",
        "안정기내장형 램프",
      ],
      "전기저장장치 구성품": ["리튬이차단전지"],
    },
    생활용품: {
      화학: ["자동차용 재생타이어"],
      생활: ["가스라이터", "물놀이기구", "비비탄 총"],
      기계금속: ["가정용 압력냄비 및 압력솥"],
      섬유: [],
      건축: [],
    },
  },
  안전확인대상제품: {
    전기용품: {
      "전선 및 전원코드": [],
      "전기기기용 스위치": {
        품목: ["전기기기용 제어소자"],
        비고: "기계·기구에 부착되는 특수구조 및 방폭형 제외",
      },
      "전원용 커패시터 및 전원필터": [],
      "전기설비용 부속품 및 연결부품": [],
      "전기용품 보호용 부품": [],
      절연변압기: {
        품목: ["고주파웰더", "전기용접기"],
        비고: "정격용량 5kVA 이하, 특수구조 제외",
      },
      전기기기: {
        품목: [
          "과일 껍질깎이",
          "전기 용해기",
          "이·미용기기",
          "전기의자 및 전동침대",
          "컴프레서",
          "전기온수매트",
          "구강청결기",
          "해충퇴치기",
          "전기집진기",
          "서비스기기",
          "전기에어커튼",
          "팬코일유닛",
          "폐열 회수 환기장치",
          "게임기구",
          "식기세척기 및 식기건조기",
          "전기훈증기",
          "수도 동결 방지기",
          "산소이온발생기",
          "전기정수기",
          "전기세척기",
          "전기헬스기구",
          "전기차 충전기",
          "가정용 전동재봉기",
          "사우나기기",
          "관상 및 애완용 전기기기",
          "기포발생기기",
          "공기청정기",
          "전기분무기",
          "물수건 마는 기기 및 포장기기",
          "주방용 전동기기",
          "전기찜질기",
          "전격 살충기",
          "자동판매기",
          "전기소독기",
          "제습기",
          "음식물처리기",
          "전기보온기 및 전기온장고",
          "유체펌프",
          "전기가열기기",
          "전기욕조",
          "그 밖에 유사한 기기",
        ],
        비고: "정격입력 10kW 이하(전기차 충전기는 예외), 방폭형 제외",
      },
      전동공구: {
        품목: ["교류전원을 사용하는 전동공구"],
        비고: "정격입력 1.5kW 이하",
      },
      "오디오·비디오 응용기기": {
        품목: [
          "텔레비전수상기",
          "디스크 플레이어",
          "오디오시스템",
          "오디오프로세서",
          "영상프로세서",
          "그 밖에 유사한 기기",
        ],
        비고: "기계·기구류에 부착되는 특수구조는 제외",
      },
      "정보·통신·사무기기": {
        품목: [
          "모니터",
          "프린터",
          "프로젝터",
          "문서 세단기",
          "천공기",
          "복사기",
          "무정전공급장치",
          "컴퓨터용 전원공급장치",
          "디지털TV",
          "코팅기",
          "노트북컴퓨터",
          "전지",
          "그 밖에 유사한 기기",
        ],
        비고: "기계·기구류에 부착되는 특수구조는 제외",
      },
      조명기기: ["백열등기구", "방전램프", "기타 조명기구", "기타 램프"],
      "전기저장장치 구성품": {
        품목: ["전력변환장치", "리튬이차전지시스템"],
        비고: "전력변환장치: 2MW 이하 / 리튬이차전지시스템: 300kWh 이하",
      },
    },
    생활용품: {
      화학: ["건전지", "자동차용 브레이크액", "자동차용 타이어"],
      생활: [
        "고령자용 보행보조차",
        "고령자용 보행차",
        "디지털 도어록",
        "롤러스포츠 보호장구",
        "스노보드",
        "스케이트보드",
        "전동보드",
        "스키용구",
        "이륜자전거",
        "헬스기구",
        "휴대용 레이저용품",
        "승차용 안전모",
        "운동용 안전모",
        "온열팩",
        "수유패드",
        "기름난로",
      ],
      기계금속: ["빙삭기", "휴대용 예초기의 날 및 보호덮개"],
      섬유: ["등산용 로프", "스포츠용 구명복"],
      건축: ["미끄럼 방지 타일", "실내용 바닥재"],
    },
  },
  공급자적합성확인대상전기용품: {
    "전선 및 전원코드": [],
    "전기기기용 스위치": [],
    "전원용 커패시터 및 전원필터": [],
    "전기설비용 부속품 및 연결부품": [],
    "전기용품 보호용부품": [],
    절연변압기: [],
    전기기기: [
      "감자 탈피기",
      "전기 정미기",
      "전기 빵 자르개",
      "애완동물 목욕기",
      "전기주류숙성기",
      "전기시계",
      "적외선ㆍ자외선방사 피부관리기",
      "전기분수기",
      "투영기",
      "착유기",
      "보풀 제거기",
      "새싹 및 콩나물 재배기",
      "전기 작동 도어록",
      "직류전원을 사용하는 공기청정기",
      "전동형 롤스크린",
      "그 밖에 유사한 기기",
    ],
    전동공구: ["직류전원을 사용하는 전동공구"],
    "오디오ㆍ비디오 응용기기": [
      "비디오카메라",
      "튜너",
      "라디오수신기",
      "리시버",
      "음성기록계",
      "음성플레이어",
      "위성방송수신기",
      "비디오폰",
      "음질조절기",
      "신호변환장치",
      "컴프레서 게이트",
      "전자시계",
      "CCTV 카메라",
      "영상수신기 및 변환기",
      "영상기록계",
      "A/V신호수신기",
      "CATV방송수신기",
      "턴테이블",
      "모듈레이터",
      "비디오게임기구",
      "오디오 및 비디오 학습기",
      "앰프",
      "편집기",
      "음성 및 영상분배기",
      "영상전송기",
      "전자악기",
      "그 밖에 유사한 기기",
    ],
    정보ㆍ통신ㆍ사무기기: [
      "스캐너",
      "지폐계수기",
      "금전등록기",
      "어학실습기",
      "전자칠판 및 보드",
      "동전계수기",
      "전동타자기",
      "전기소자기",
      "교통카드 충전기",
      "번호표 발행기",
      "생활무선국용 무전기",
      "무선기기",
      "IPTV용 셋톱박스",
      "디지털 CATV 셋톱박스",
      "디지털 재변조형 주파수변환기",
      "A/D 및 D/A 신호변환기",
      "지상파텔레비전방송 신호처리기",
      "재단기",
      "실물화상기",
      "입체영상기",
      "휴대형 무선통신기기",
      "전화기",
      "팩시밀리기기",
      "전화기능 내장 복합단말기기",
      "공중전화 데이터전송 단말기",
      "신용카드조회 단말기기",
      "특정 용도의 단말기기",
      "위치기반 무선기기",
      "원격제어방송기기",
      "제본기",
      "그 밖에 유사한 기기",
    ],
    조명기기: ["형광램프용 스타터"],
    "전기저장장치 구성품": [],
  },
  공급자적합성확인대상생활용품: {
    화학: ["폴리염화비닐관"],
    생활: [
      "가정용 서랍장 및 사무용 파일링 캐비닛",
      "롤러스케이트",
      "바퀴 달린 운동화",
      "모터 달린 보드",
      "창문 블라인드",
      "쌍꺼풀용 테이프",
      "속눈썹 열 성형기",
      "인조속눈썹",
      "쇼핑카트",
      "휴대용 사다리",
      "인라인롤러스케이트",
      "킥보드",
    ],
    기계금속: ["자동차용 휴대용 잭"],
    섬유: [],
    건축: ["물탱크"],
  },
};

export const PROMPT = {
  init: {
    system: `You are a frontline customer support agent, specializing in general inquiries related to KC certification.
    Be concise in your responses.
    You can chat with customers and help them with basic questions, but if the customer is having a certification problem, do not try to answer the question directly or gather information.
    Instead, immediately transfer them to the **CERTIFICATION SUPPORT TEAM** by asking the user to hold for a moment. Otherwise, just respond **CONVERSATIONALLY**. every response should be in korean`,
  },
  routing: {
    system: `You are an expert customer support routing system. Your job is to detect whether a customer support representative is routing a user to a **CERTIFICATION SUPPORT TEAM** or if they are just responding **CONVERSATIONALLY**.`,

    user: `The previous conversation is an interaction between a customer support representative and a user. Extract whether the representative is routing the user to a **CERTIFICATION SUPPORT TEAM**, or whether they are just responding **CONVERSATIONALLY**. Respond with a JSON object containing a single key called "nextRepresentative" with one of the following values:
    If they want to route the user to the **CERTIFICATION SUPPORT TEAM**, respond only with the word "CERTIFICATION"
    Otherwise, respond only with the word "RESPOND".`,
  },
  certification: {
    system: `You are an expert certification support specialist for KC certification, a company that sells computers. Help the user to the best of your ability, but be concise in your responses. 
    You are a classifier tasked with identifying the required KC certification type for a product item provided by the user. Your classification **must** be based **solely** on the provided 'KC Certification Product Standard Table'. Do not use any information outside of this table or your prior knowledge.
    Help the user to the best of your ability, but be concise in your responses.
    ---------
    KC Certification Product Standard Table:
    ${CRITERIA}
    ---------
    EXAMPLES:
    - 질문하신 '무선 진공 청소기' 제품은 '전기청소기' 카테고리에 해당하며 '안전인증대상제품'입니다.
    - 질문하신 제품은 '쌍꺼풀용 테이프' 카테고리에 해당하며 '공급자적합성확인대상생활용품'입니다.
    - 질문하신 제품은 '고령자용 보행보조차' 카테고리에 해당하며 '공급자적합성확인대상전기용품' 입니다.
    - 적합한 품목이 없어서 KC인증 대상인지 확인이 어렵습니다.
    - 질문하신 제품은 '전기온수매트' 카테고리에 해당하며 '안정확인대상제품'입니다.
    - '실물화상기' 제품은 '정보ㆍ통신ㆍ사무기기' 카테고리이며 '안전확인' 인증을 받아야합니다.
    `,
  },
};
